import Head from 'next/head'
import { useState,useEffect } from 'react';
import { createClient } from '@supabase/supabase-js'
import { MainContext} from './contexts/MainContext';
import ProductsPg from './components/ProductsPg';

export async function getStaticProps(){
  const supabaseAdmin = createClient(
    process.env.NEXT_PUBLIC_SUPABASE_URL || '',
    process.env.SUPABASE_SERVICE_ROLE_KEY || ''
  );
  return {
    props:{},
  }
  }

export default function Home() {
  const [product,setProduct] = useState([])
  const [loading,isLoading] = useState(true)
 


  useEffect(()=>{
    fetch('https://fakestoreapi.com/products')
            .then(res=>res.json())
            .then(data=>{

    setProduct(data);
    isLoading(false);
    })
    .catch(err => console.log(err))
  }, []) 

  return (
    <>
      <Head>
        <title>Ecommerce app</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
      </Head>
      <div>
      
        <ProductsPg data={product} />
      </div>
    </>
  )
}
